version: '3.1'

services:
  thunderdome:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    ports:
      - "18080:8080"
    depends_on:
      - db
    links:
      - db
    networks:
      - asgard
    environment:
      APP_DOMAIN: ".127.0.0.1"
      COOKIE_SECURE: "false"
      SMTP_SECURE: "false"
      SMTP_HOST: mail
      SMTP_PORT: 1025
      DB_NAME: thunderdome
      DB_USER: thor
      DB_PASS: odinson
    volumes:
      - ./etc:/etc/thunderdome
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: thunderdome
      POSTGRES_USER: thor
      POSTGRES_PASSWORD: odinson
    ports:
      - "15432:5432"
    volumes:
      - thunderdome_data:/var/lib/postgresql/data
    networks:
      - asgard
  mail:
    image: maildev/maildev:2.1.0    
    ports:
      - "11080:1080"
      - "11025:1025"
    networks:
      - asgard
  ngrok:
    env_file:
      - .env
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "--url=${NGROK_DOMAIN}"
      - "http://host.docker.internal:18080"
      - "--log=stdout"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"

networks:
  asgard:

volumes:
  thunderdome_data:
